apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-dist
spec:
    replicas: 1
    selector:
      matchLabels:
        app: conv-dist
    template:
      metadata:
        labels:
          app: conv-dist
      spec:
        containers:
        - name: conv-dist
          image: ivan3j/conv-dist:v1
          ports: 80
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: conv-dist
spec:
  selector:
    app: conv-dist
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  type: NodePort
  